-- TH-107: reviewed job-to-be-done taxonomy for the curated repository dataset.
-- Only explicitly curated slugs are activated; free-form AI/editorial proposals remain proposed.

INSERT INTO use_cases (slug, title, description, status) VALUES
  ('tool-using-ai-agents', 'Tool-using AI agents', 'Build model-driven agents that invoke controlled tools or application actions.', 'active'),
  ('multi-step-ai-automation', 'Multi-step AI automation', 'Automate tasks that require multiple model, tool, or decision steps.', 'active'),
  ('agent-orchestration', 'Agent orchestration', 'Coordinate agent state, tools, execution flow, and reusable runtime behavior.', 'active'),
  ('browser-task-automation', 'Browser task automation', 'Automate navigation and interaction in a real web browser.', 'active'),
  ('agentic-web-navigation', 'Agentic web navigation', 'Give AI or automation systems a controlled browser execution boundary.', 'active'),
  ('end-to-end-web-testing', 'End-to-end web testing', 'Exercise complete browser-visible workflows against web applications.', 'active'),
  ('multi-step-workflow-automation', 'Multi-step workflow automation', 'Run repeatable workflows spanning multiple tasks or services.', 'active'),
  ('integration-orchestration', 'Integration orchestration', 'Coordinate actions across connectors, APIs, and service boundaries.', 'active'),
  ('scheduled-background-jobs', 'Scheduled background jobs', 'Execute repeatable background work from schedules or asynchronous triggers.', 'active'),
  ('web-data-collection', 'Web data collection', 'Collect data repeatedly from authorized web sources.', 'active'),
  ('crawling-and-content-extraction', 'Crawling and content extraction', 'Traverse pages and convert web content into structured output.', 'active'),
  ('public-web-monitoring', 'Public web monitoring', 'Monitor authorized public web sources while respecting terms and rate limits.', 'active'),
  ('document-and-content-extraction', 'Document and content extraction', 'Convert heterogeneous documents or content into structured information.', 'active'),
  ('data-normalization-pipelines', 'Data normalization pipelines', 'Normalize extracted or heterogeneous data for downstream systems.', 'active'),
  ('research-data-preparation', 'Research data preparation', 'Prepare source material as structured reusable research data.', 'active'),
  ('private-self-hosted-deployment', 'Private self-hosted deployment', 'Operate an application on infrastructure controlled by the adopter.', 'active'),
  ('data-control-and-sovereignty', 'Data control and sovereignty', 'Prioritize deployment ownership and control over data location.', 'active'),
  ('internal-tools-and-knowledge', 'Internal tools and knowledge', 'Run software for internal-team workflows, tools, or knowledge systems.', 'active'),
  ('local-llm-inference', 'Local LLM inference', 'Run language-model inference on local or self-managed compute.', 'active'),
  ('production-model-serving', 'Production model serving', 'Expose model inference to applications through a production serving boundary.', 'active'),
  ('private-knowledge-rag', 'Private knowledge RAG', 'Ground AI applications in retrieved private or external knowledge.', 'active'),
  ('semantic-search', 'Semantic search', 'Retrieve conceptually relevant information from indexed knowledge.', 'active'),
  ('document-question-answering', 'Document question answering', 'Answer questions using retrieved context from documents or knowledge sources.', 'active'),
  ('developer-workflow-automation', 'Developer workflow automation', 'Reduce friction in repetitive development and engineering workflows.', 'active'),
  ('developer-tool-integration', 'Developer tool integration', 'Integrate reusable software capabilities into developer workflows.', 'active'),
  ('evaluation-and-quality-gates', 'Evaluation and quality gates', 'Run repeatable evaluations or checks before software or AI changes advance.', 'active'),
  ('regression-testing', 'Regression testing', 'Detect behavior changes across versions with repeatable test suites.', 'active'),
  ('ai-application-observability', 'AI application observability', 'Inspect traces, evaluations, runtime behavior, and quality signals in AI applications.', 'active'),
  ('trace-and-evaluation-analysis', 'Trace and evaluation analysis', 'Analyze execution traces and evaluation results for diagnosis and improvement.', 'active'),
  ('programmatic-image-generation', 'Programmatic image generation', 'Generate or transform visual assets through software-driven pipelines.', 'active'),
  ('generative-media-pipelines', 'Generative media pipelines', 'Compose image, video, audio, or content generation into automated production pipelines.', 'active'),
  ('automated-video-production', 'Automated video production', 'Create, assemble, or transform video through automated software workflows.', 'active'),
  ('video-postproduction-automation', 'Video post-production automation', 'Automate editing, subtitle, avatar, or media-processing stages after generation or capture.', 'active'),
  ('content-production-automation', 'Content production automation', 'Automate repeatable stages that assemble, transform, or package content.', 'active'),
  ('api-integration-layer', 'API integration layer', 'Expose, adapt, or bridge programmatic interfaces between systems.', 'active'),
  ('tool-protocol-bridging', 'Tool and protocol bridging', 'Bridge compatible APIs, tools, or protocols across integration boundaries.', 'active')
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  status = 'active',
  updated_at = now();
